project:
  type: website
  output-dir: docs

website:
  title: "Pet Classifier"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - classify.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true